In [6]:
import pandas as pd
df_fe = pd.read_csv("/home/abishek/Documents/GUVI Projects/EcoType-Forest-Cover/data/processed/capped_forest_cover_data.csv")

In [10]:
df_fe.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Cover_Type,Wilderness_Area,Soil_Type
0,2596.0,51,3,258.0,0,510,221.0,232,148,6279,Aspen,1,29
1,2590.0,56,2,212.0,-6,390,220.0,235,151,6225,Aspen,1,29
2,2804.0,139,9,268.0,65,3180,234.0,238,135,6121,Lodgepole Pine,1,12
3,2785.0,155,18,242.0,117,3090,238.0,238,122,6211,Lodgepole Pine,1,30
4,2595.0,45,2,153.0,-1,391,220.0,234,150,6172,Aspen,1,29

In [11]:
df_fe.tail()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,Cover_Type,Wilderness_Area,Soil_Type
145885,2834.0,88,8,376.0,44,2552,232.0,227,128,1595,Lodgepole Pine,1,29
145886,2832.0,68,4,390.0,44,2522,224.0,231,142,1572,Lodgepole Pine,1,29
145887,2829.0,80,7,390.0,33,2492,229.0,228,133,1550,Lodgepole Pine,1,29
145888,2826.0,121,7,379.0,30,2462,232.0,234,135,1528,Lodgepole Pine,1,29
145889,2823.0,132,12,371.0,27,2432,239.0,234,123,1506,Lodgepole Pine,1,1